project_name: "kinase_activity_estimation"

general:
  PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "johnson9990", "johnson15", "phosformer5", "phosformer10", "phosformer15"]
  merged: ["phosphositeplus_networkin", "phosphositeplus_iKiPdb", "phosphositeplus_johnson15", "phosphositeplus_phosformer15", "shuffledKIP", "shuffledNET"]

cptac:
  datasets: ["ucec", "luad", "lscc", "hnscc", "gbm", "ccrcc", "brca"]
  cptac_PKNs: ["phosphositeplus"] #, "phosphositeplus_networkin", "phosphositeplus_iKiPdb", "shuffled"
  normalisation: ["original"] #, "global", "protein", "site", "subtract", "unnorm"

hernandez:
  hernandez_PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled"]
  hernandez_PKNs_subset: ["phosphositeplus", "phosphositeplus_networkin", "phosphositeplus_iKiPdb"]
  hernandez_methods: ["KARP", "KS", "KSEA_z", "PC1", "RoKAI_z", "Wilcox", "fgsea", "mean", "median", "mlm","norm_wmean","number_of_targets","rokai_lm","ulm","viper","wsum", "ptmsea"] # "INKA", "UQ", "norm_fgsea"
  hernandez_overlap: ["scaled", "raw"] #scaled is equivalent to all #"scaled_subset", "subset"

hijazi:
  hijazi_PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled"]
  hernandez_PKNs_subset: ["phosphositeplus", "phosphositeplus_networkin", "phosphositeplus_iKiPdb"]
  hernandez_methods: ["KARP", "KS", "KSEA_z", "PC1", "RoKAI_z", "Wilcox", "fgsea", "mean", "median", "mlm","norm_wmean","number_of_targets","rokai_lm","ulm","viper","wsum", "ptmsea"] # "INKA", "UQ", "norm_fgsea"
  hernandez_overlap: ["scaled", "raw"] #scaled is equivalent to all #"scaled_subset", "subset"

figures:
  PKN_figure1: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin"]
  PKN_figure2: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled"]
