project_name: "kinase_activity_estimation"

activity_estimation:
  datasets: ["ucec", "luad", "lscc", "hnscc", "gbm", "ccrcc", "brca"]
  PKNs: ["omnipath", "GPSnetworkin", "GPS", "networkin", "phosphositeplus", "ptmsigdb", "iKiPdb"]

decryptm:
  decryptm_set: ["10_Kinase_Inhibitors", "Combination_Treatments_AZD4547_Gefitinib", "Combination_Treatments_AZD4547_Lapatinib", "Combination_Treatments_Selumetinib_MK2206", "Dasatinib_Triplicates", "BCRABL_Inhibitors", "HER2_Inhibitors", "3_EGFR_Inhibitors"]
