project_name: "kinase_activity_estimation"

general:
  PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "johnson9990", "johnson15", "phosformer5", "phosformer10", "phosformer15"]
  merged: ["phosphositeplus_networkin", "phosphositeplus_iKiPdb", "phosphositeplus_johnson15", "phosphositeplus_phosformer15", "shuffledKIP", "shuffledNET"]

cptac:
  datasets: ["ucec", "luad", "lscc", "hnscc", "gbm", "ccrcc", "brca"]
  cptac_PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "phosphositeplus_networkin", "phosphositeplus_iKiPdb", "phosphositeplus_johnson15", "phosphositeplus_phosformer15", "shuffledKIP", "shuffledNET"]
  normalisation: ["global", "protein", "site", "subtract", "unnorm"] #, "global", "protein", "site", "subtract", "unnorm"
  normalisation_PKNs: ["phosphositeplus"]

perturbation:
  PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "GSknown", "combined", "shuffled2"]
  subset: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "GSknown", "combined"]
  predicted: ["phosphositeplus", "GSknown_networkin", "GSknown_iKiPdb", "combined_networkin", "combined_iKiPdb"]
  GSknownSub: ["GSknown", "GSknown_networkin", "GSknown_iKiPdb", "combined"]
  combinedSub: ["combined", "combined_networkin", "combined_iKiPdb"]
  johnson1Sub: ["GSknown", "GSknown_johnson15", "GSknown_phosformer15"]
  johnson2Sub: ["combined", "combined_johnson15", "combined_phosformer15"]
  all: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled2", "GSknown", "combined", "GSknown_networkin", "GSknown_iKiPdb", "combined_networkin", "combined_iKiPdb"]
  methods: ["chisq","fgsea","fisher", "KARP", "KS", "KSEA", "lmRoKAI", "mean", "median", "mlm", "norm_mean", "number_of_targets", "PCA", "ptmsea", "ulm", "UQ", "viper", "wilcox","zscore"] # "INKA", "UQ", "norm_fgsea"
  methods_johnson: ["chisq","fgsea","fisher", "KARP", "KS", "KSEA", "lmRoKAI", "mean", "median", "mlm", "norm_mean", "number_of_targets", "PCA", "ptmsea", "ulm", "UQ", "viper", "wilcox","zscore"]
  methods_subset: ["chisq","fgsea","fisher", "KARP", "KS", "KSEA", "lmRoKAI", "mean", "median", "mlm", "norm_mean", "number_of_targets", "PCA", "ptmsea", "ulm", "UQ", "viper", "wilcox","zscore"]

figures:
  coverage: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "GSknown"]
  evaluation: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "GSknown", "shuffled2"]
  evaluation_cptac: ["known", "gps", "ikip", "nwkin", "omni", "psp", "ptmsig"]
  PKN_figure1: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "nwkin", "omni", "psp", "ptmsig"]
  PKN_figure2: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled"]
