project_name: "kinase_activity_estimation"

general:
  PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "johnson9990", "johnson15", "phosformer5", "phosformer10", "phosformer15"]
  merged: ["phosphositeplus_networkin", "phosphositeplus_iKiPdb", "phosphositeplus_johnson15", "phosphositeplus_phosformer15", "shuffledKIP", "shuffledNET"]

cptac:
  datasets: ["ucec", "luad", "lscc", "hnscc", "gbm", "ccrcc", "brca"]
  cptac_PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "phosphositeplus_networkin", "phosphositeplus_iKiPdb", "phosphositeplus_johnson15", "phosphositeplus_phosformer15", "shuffledKIP", "shuffledNET"]
  normalisation: ["global", "protein", "site", "subtract", "unnorm"] #, "global", "protein", "site", "subtract", "unnorm"
  normalisation_PKNs: ["phosphositeplus"]

perturbation:
  PKNs: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "GSknown", "combined", "shuffled2"]
  predicted: ["phosphositeplus", "phosphositeplus_networkin", "phosphositeplus_iKiPdb"]
  johnson: ["phosphositeplus", "phosphositeplus_johnson15", "phosphositeplus_phosformer15"]
  all: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled", "johnson15", "phosformer15", "phosphositeplus_networkin", "phosphositeplus_iKiPdb", "phosphositeplus_johnson15", "phosphositeplus_phosformer15"]
  methods: ["chisq","fgsea","fisher", "KARP", "KS", "KSEA", "lmRoKAI", "mean", "median", "mlm", "norm_mean", "number_of_targets", "PCA", "ptmsea", "ulm", "UQ", "viper", "wilcox","zscore"] # "INKA", "UQ", "norm_fgsea"
  methods_johnson: ["KSEA_z", "RoKAI_z", "fgsea", "mean", "number_of_targets", "ptmsea"]
  methods_subset: ["KSEA_z", "RoKAI_z", "fgsea", "mean", "number_of_targets", "ptmsea"]

figures:
  PKN_figure1: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin"]
  PKN_figure2: ["omnipath", "phosphositeplus", "ptmsigdb", "GPS", "iKiPdb", "networkin", "shuffled"]
